Local repo
fieldmade/di-protobuf pull request #15
Opened 2021-12-01 13:48 UTC by stasmantach

2021-12-01 14:30 UTC, kamilmsoprasteria requested changes

2021-12-01 14:30 UTC, kamilmsoprasteria commented on fmdi/repository_local/v1beta1/repository_part.proto
> +message RepositoryPart {
maybe rename it to LocalPart or InternalPart ? @srs ?

2021-12-01 14:30 UTC, kamilmsoprasteria commented on fmdi/repository_local/v1beta1/repository_part.proto
> +    // Reference id for the organization
```suggestion
    // Reference id of the part
```
?
why "for the organization"?

2021-12-01 14:30 UTC, kamilmsoprasteria commented on fmdi/repository_local/v1beta1/repository_part.proto
> +}
should there be a refid filter?

2021-12-01 14:30 UTC, kamilmsoprasteria commented on fmdi/repository_local/v1beta1/repository_part.proto
> +    // Reference id for the organization
```suggestion
    // Reference id of the part
```

2021-12-01 14:30 UTC, kamilmsoprasteria commented on fmdi/repository_local/v1beta1/repository_part.proto
> +    string ref_id = 1;
I think all those string fields should be `google.protobuf.StringValue` to make them optional on update

2021-12-01 14:46 UTC, stasmantach commented on fmdi/repository_local/v1beta1/repository_part.proto
> +message RepositoryPart {
I thought about it. and actually started with LocalParts.
The logic with the repository is that. you have your organization's repository here you can add whatever. 
And then you have Marketplace parts those are super well-validated and available to others.

2021-12-01 14:47 UTC, stasmantach commented on fmdi/repository_local/v1beta1/repository_part.proto
> +    // Reference id for the organization
of the part for the organization

2021-12-01 14:52 UTC, stasmantach commented on fmdi/repository_local/v1beta1/repository_part.proto
> +}
Don't think so. Part filtering in the future would be complex. And it would be a separate facet-based search thing. For filtering, I would create in the future search for parts and there would be search terms and other arguments for faceting and ordering.

2021-12-01 15:03 UTC, kamilmsoprasteria commented on fmdi/repository_local/v1beta1/repository_part.proto
> +message RepositoryPart {
I'm not sure, let's wait for Sten's opinion
For me, all are "repository parts" in the context of repository (when you edit them), but some are internal, and some  are "parts in the marketplace" when you publish them

2021-12-02 12:46 UTC, kamilmsoprasteria approved these changes

2021-12-02 13:03 UTC, merged